name: CI
on: 
  push
jobs: 
  check_simulators:
    name: Check Simulators
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Check Sim
      run: echo xcrun simctl list &>/dev/null
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Choose Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Build App
      run: xcodebuild clean build test -project SeeEyeSeeDee.xcodeproj -scheme "SeeEyeSeeDee" -target SeeEyeSeeDee -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
  
