name: CI
on: 
  push
jobs: 
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Choose Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Build App
      run: xcodebuild -scheme "SeeEyeSeeDee" -target SeeEyeSeeDee -sdk iphonesimulator clean build
      
  tests:
    name: Run Tests
    runs-on: macos-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: Choose Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
    - name: Run Tests
      run: xcodebuild -scheme "SeeEyeSeeDee" -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=14.0' test
